### ISSUE TITLE
Help with accessing Array elements.....

### ISSUE THREAD

**Issue by danoyoung** [micha/jsawk#15]
Hello, I was wondering if someone might be able to help me with jsawk and how to access/print each element in the below log array w/n a json document.  I'm having trouble understanding how to do this....

{
    "device_id": "4FB9B235848E2E6E73A507186771A3E3",
    "logs": [
        {
            "id": 21,
            "activity": "physician/249",
            "timestamp": "2012-02-04 00:07:26"
        },
        {
            "id": 22,
            "activity": "physician",
            "timestamp": "2012-02-04 00:08:07"
        },
        {
            "id": 23,
            "activity": "physician/1196",
            "timestamp": "2012-02-04 00:08:17"
        }
    ],
    "user_device": "Apple/iPhone4,1/iPhone OS/5.0.1/3.3"
}

**Comment by cyberhuman** [comment]
For those curious:
```
jsawk -b 'return this[0].logs' -a 'return [this]' '<script>'
```
