### ISSUE TITLE
js: uncaught JavaScript runtime exception: ReferenceError: "readline" is not defined.

### ISSUE THREAD

**Issue by dhainsfdc** [micha/jsawk#8]
I am trying to use jsawk on Ubuntu 10.04 but keep on getting the above error. I built spidermonkey v 1.8.5 (1.0.0) from src (make install) and that is what jsawk should be picking up. Is readline in a js library that's missing?

**Comment by buddhashrestha** [comment]
i have used the reference of http://roaet.com/installing-spidermonkey-on-ubuntu-13-04-from-source/ to install spidermonkey js. also the binary js (according to the above site) and other file like js.cpp etc are found inside /js/shell. but still after the installation process, it only shows the option that:

The program 'js' can be found in the following packages:

    rhino
    nodejs

Try: sudo apt-get install < select packages>

I dont know what to do ?? please help out.

Thanks.

**Comment by ghost** [comment]
I got it to work with RHINO

Changed the following lines:
--- /usr/bin/jsawk.old  2015-04-17 21:51:57.557073345 +0000
+++ /usr/bin/jsawk  2015-04-17 21:52:09.973072920 +0000
@@ -1221,8 +1221,12 @@

   var input="";
-  importPackage(java.io);
-  importPackage(java.lang);
-  var stdin = new BufferedReader( new InputStreamReader(System['in']) )
  +
  for (var i=0; i<inputLines; i++) {
-    var line=readline();
-    var line=stdin.readLine();
   input += (line ? line : "");
   input += "\n";
  }

**Comment by flamusdiu** [comment]
@wtorres-TLG you might want to surround your code with code blocks. Github markup eating up the format. =\

**Comment by harsh-verma** [comment]
Use following command and this will work in ubuntu 👍 
->> apt-get install nodejs
->> sudo apt-get install libmozjs-24-bin; sudo ln -sf /usr/bin/js24 /usr/bin/js
